#include "include/token.h"
#include <stdlib.h>
#include <string.h>

char *tokentype_to_string(TokenType type) {
  switch (type) {

  case (TOKEN_LEFTPAREN):
    return "LEFT_PAREN";
  case (TOKEN_RIGHT_PAREN):
    return "RIGHT_PAREN";
  case (TOKEN_LEFT_BRACE):
    return "LEFT_BRACE";
  case (TOKEN_RIGHT_BRACE):
    return "RIGHT_BRACE";
  case (TOKEN_COMMA):
    return "COMMA";
  case (TOKEN_DOT):
    return "DOT";
  case (TOKEN_MINUS):
    return "MINUS";
  case (TOKEN_PLUS):
    return "PLUS";
  case (TOKEN_SEMICOLON):
    return "SEMICOLON";
  case (TOKEN_SLASH):
    return "SLASH";
  case (TOKEN_STAR):
    return "STAR";
  case (TOKEN_BANG):
    return "BANG";
  case (TOKEN_BANG_EQUAL):
    return "BANG_EQUAL";
  case (TOKEN_EQUAL):
    return "EQUAL";
  case (TOKEN_EQUAL_EQUAL):
    return "EQUAL_EQUAL ";
  case (TOKEN_GREATER):
    return "GREATER";
  case (TOKEN_GREATER_EQUAL):
    return "GREATER_EQUAL";
  case (TOKEN_LESS):
    return "LESS";
  case (TOKEN_LESS_EQUAL):
    return "LESS_EQUAL";
  case (TOKEN_IDENTIFIER):
    return "IDENTIFIER";
  case (TOKEN_STRING):
    return "STRING";
  case (TOKEN_NUMBER):
    return "NUMBER";
  case (TOKEN_AND):
    return "AND";
  case (TOKEN_CLASS):
    return "CLASS";
  case (TOKEN_ELSE):
    return "ELSE";
  case (TOKEN_FALSE):
    return "FALSE";
  case (TOKEN_FUNC):
    return "FUN";
  case (TOKEN_FOR):
    return "FOR";
  case (TOKEN_IF):
    return "IF";
  case (TOKEN_NIL):
    return "NIL";
  case (TOKEN_OR):
    return "OR";
  case (TOKEN_PRINT):
    return "PRINT";
  case (TOKEN_RETURN):
    return "RETURN";
  case (TOKEN_SUPER):
    return "SUPER";
  case (TOKEN_THIS):
    return "THIS";
  case (TOKEN_TRUE):
    return "TRUE";
  case (TOKEN_VAR):
    return "VAR";
  case (TOKEN_WHILE):
    return "WHILE";
  case (TOKEN_EOF):
    return "EOF_TOKEN";
  case (TOKEN_INVALID):
    return "INVALID";
  }
}
